-- Supabase Schema for Empower App

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    mobile TEXT UNIQUE NOT NULL,
    verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Investments Table
CREATE TABLE IF NOT EXISTS public.investments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES public.users(mobile) ON DELETE CASCADE,
    plan_name TEXT NOT NULL,
    base_amount NUMERIC NOT NULL,
    expected_return NUMERIC NOT NULL,
    days INTEGER NOT NULL,
    daily_roi NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, verifying, active, completed, rejected
    payment_method TEXT,
    upi_id TEXT,
    utr_number TEXT,
    receipt_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES public.users(mobile) ON DELETE CASCADE,
    type TEXT NOT NULL, -- deposit, withdrawal, interest, referral
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'success', -- success, pending, failed
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. OTPs Table
CREATE TABLE IF NOT EXISTS public.otps (
    mobile TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Admin Settings Table
CREATE TABLE IF NOT EXISTS public.admin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upi_id TEXT,
    qr_code_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

-- 7. Create Policies (Permissive for Demo - You can tighten these later)

-- Users Policies
CREATE POLICY "Allow public select on users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert on users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on users" ON public.users FOR UPDATE USING (true);

-- Investments Policies
CREATE POLICY "Allow public select on investments" ON public.investments FOR SELECT USING (true);
CREATE POLICY "Allow public insert on investments" ON public.investments FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on investments" ON public.investments FOR UPDATE USING (true);

-- Transactions Policies
CREATE POLICY "Allow public select on transactions" ON public.transactions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on transactions" ON public.transactions FOR INSERT WITH CHECK (true);

-- OTPs Policies
CREATE POLICY "Allow public all on otps" ON public.otps FOR ALL USING (true);

-- Admin Settings Policies
CREATE POLICY "Allow public select on admin_settings" ON public.admin_settings FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update on admin_settings" ON public.admin_settings FOR ALL USING (true);

-- 8. Grant Permissions to Anon and Authenticated Roles
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
